#经常会变化的放在这个文件
#对外端口
server:
  port: 8001
#单独访问时，可以使用访问路径，和网关配置的路由一样
#  servlet:
#    context-path: /api/user-center
spring:
  #微服务配置
  cloud:
    nacos:
      discovery:
#        server-addr: 106.12.105.123:8848
        server-addr: 127.0.0.1:8848
  application:
    name: auth-api
  # 数据库配置
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring_cloud_demo?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 111qqq

#mybatis-plus默认配置
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  #类别名，支持通配符 * 或者 ; 分割
  typeAliasesPackage: com.weng.**.mapper

#应用属性
app:
  default-password: 123456
